### ISSUE TITLE
Compile instructions?

### ISSUE THREAD

**Issue by elektor-labs** [breedj/Elektor-Network-Connected-Signal-Analyser#1]
The C# projects don't compile on my machine. Visual Studio Express 2010 complains about missing System.Net.Http
Furthermore, it doesn't like SignalAnalyzer.cs line 229 (and a whole lot more) for which it gives many "invalid token" errors (for the '=' in this case):

`public WindowingTypes WindowType { get; set; } = WindowingTypes.Square;
`

I suppose these will all go away with a simple explanation, an extra file or something to install first on the user's PC?

**Comment by breedj** [comment]
Yes, I think the explanation is simple. As stated in the project description you have to use Visual Studio 2015. It does not work with 2010.
You can download VS 2015 here: https://www.visualstudio.com/en-us/products/vs-2015-product-editions.aspx
The project needs .NET 4.0 which comes with VS 2015.

I hope that helps.

**Comment by breedj** [comment]
Be aware of the fact that the current client does not detect boards which have the original firmware. I will change that this weekend so the new software will work with the old firmware. 
For now you have to either use the new firmware from this github project or you might get it to work by editing the app.config file and enter the ip address of your board between the value tags. Like this:
....

```
<setting name="IPanalyzer" serializeAs="String">
                <value>192.168.1.112</value>
</setting> 
```

....

If you've done this do not click the find button, just the connect button, as it might change this setting.

**Comment by breedj** [comment]
For the time being you can also hard code the ip in the software of coarse.

**Comment by breedj** [comment]
The application has been changed. The old firmware is supported as well.

**Comment by elektor-labs** [comment]
With Visual Studio 2015 it does indeed compile without problems (as long as you select the project SignalAnalyzerApplication). Tried the latest version of the code.
